# 定义PV
apiVersion: v1
kind: PersistentVolume
metadata:
  name: www-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 2Gi    
  nfs:
    path: /nfs/data/www
    server: 192.168.10.99
